name: C++ CI Workflow

on:
 workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build project
      run: |
        mkdir build
        cd build
        cmake ..
        make
      env: 
        CC: clang
        CXX: clang++

    - name: Run tests
      run: |
        cd build
        ctest
